# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160517050722 on 2016-05-19 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfinal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='subcat',
            field=models.TextField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
